/* Generated By:JavaCC: Do not edit this line. MooplParser.java */
  import syntaxtree.*;
  import syntaxtree.interp.*;
  import static syntaxtree.ExpOp.Op;
  import java.util.Arrays;
  import java.util.List;
  import java.util.LinkedList;
  import java.util.ArrayList;
  public class MooplParser implements MooplParserConstants {

  final public void testTokens() throws ParseException {
  Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
      case CLASS:
      case EXTENDS:
      case RETURN:
      case BOOL:
      case TRUE:
      case FALSE:
      case SELF:
      case INT:
      case ARRAYOF:
      case IF:
      case THEN:
      case ELSE:
      case WHILE:
      case DO:
      case OUTPUT:
      case LENGTH:
      case NEW:
      case OBJECT:
      case ISNULL:
      case DOT:
      case COMMA:
      case EQUALS:
      case OPENSBR:
      case CLOSESBR:
      case OPENBRACE:
      case CLOSEBRACE:
      case OPENPAREN:
      case CLOSEPAREN:
      case ENDST:
      case NOT:
      case OP:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
      case CLASS:
      case EXTENDS:
      case RETURN:
      case BOOL:
      case TRUE:
      case FALSE:
      case SELF:
      case INT:
      case ARRAYOF:
      case IF:
      case THEN:
      case ELSE:
      case WHILE:
      case DO:
      case OUTPUT:
      case LENGTH:
      case NEW:
      case OBJECT:
      case ISNULL:
      case DOT:
      case COMMA:
      case EQUALS:
      case OPENSBR:
      case CLOSESBR:
      case OPENBRACE:
      case CLOSEBRACE:
      case OPENPAREN:
      case CLOSEPAREN:
      case ENDST:
      case NOT:
      case OP:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
          t = jj_consume_token(PROC);
          break;
        case FUN:
          t = jj_consume_token(FUN);
          break;
        case CLASS:
          t = jj_consume_token(CLASS);
          break;
        case OP:
          t = jj_consume_token(OP);
          break;
        case EXTENDS:
          t = jj_consume_token(EXTENDS);
          break;
        case RETURN:
          t = jj_consume_token(RETURN);
          break;
        case BOOL:
          t = jj_consume_token(BOOL);
          break;
        case TRUE:
          t = jj_consume_token(TRUE);
          break;
        case FALSE:
          t = jj_consume_token(FALSE);
          break;
        case SELF:
          t = jj_consume_token(SELF);
          break;
        case INT:
          t = jj_consume_token(INT);
          break;
        case ARRAYOF:
          t = jj_consume_token(ARRAYOF);
          break;
        case IF:
          t = jj_consume_token(IF);
          break;
        case THEN:
          t = jj_consume_token(THEN);
          break;
        case ELSE:
          t = jj_consume_token(ELSE);
          break;
        case WHILE:
          t = jj_consume_token(WHILE);
          break;
        case DO:
          t = jj_consume_token(DO);
          break;
        case OUTPUT:
          t = jj_consume_token(OUTPUT);
          break;
        case LENGTH:
          t = jj_consume_token(LENGTH);
          break;
        case NEW:
          t = jj_consume_token(NEW);
          break;
        case OBJECT:
          t = jj_consume_token(OBJECT);
          break;
        case ISNULL:
          t = jj_consume_token(ISNULL);
          break;
        case DOT:
          t = jj_consume_token(DOT);
          break;
        case COMMA:
          t = jj_consume_token(COMMA);
          break;
        case EQUALS:
          t = jj_consume_token(EQUALS);
          break;
        case OPENSBR:
          t = jj_consume_token(OPENSBR);
          break;
        case CLOSESBR:
          t = jj_consume_token(CLOSESBR);
          break;
        case OPENBRACE:
          t = jj_consume_token(OPENBRACE);
          break;
        case CLOSEBRACE:
          t = jj_consume_token(CLOSEBRACE);
          break;
        case OPENPAREN:
          t = jj_consume_token(OPENPAREN);
          break;
        case CLOSEPAREN:
          t = jj_consume_token(CLOSEPAREN);
          break;
        case ENDST:
          t = jj_consume_token(ENDST);
          break;
        case NOT:
          t = jj_consume_token(NOT);
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        System.out.println("Recognised as valid token: " + t.image);
        break;
      case INTEGER_LITERAL:
        t = jj_consume_token(INTEGER_LITERAL);
        System.out.println("Recognised as INTEGER_LITERAL: " + t.image);
        break;
      case ID:
        t = jj_consume_token(ID);
        System.out.println("Recognised as ID: " + t.image);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public Program nt_Program() throws ParseException {
  ProcDecl pd;
  ClassDecl cd;
  List<ProcDecl> pl = new ArrayList<ProcDecl>();
  List<ClassDecl> cl = new ArrayList<ClassDecl>();
    label_2:
    while (true) {
      pd = nt_ProcDecl();
                     pl.add(pd);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      cd = nt_ClassDecl();
                                                         cl.add(cd);
    }
    {if (true) return new Program(pl, cl);}
    throw new Error("Missing return statement in function");
  }

  final public ClassDecl nt_ClassDecl() throws ParseException {
  Token t, t1=null;
  FieldDecl fd;
  MethodDecl md;
  List<FieldDecl> fl = new ArrayList<FieldDecl>();
  List<MethodDecl> ml = new ArrayList<MethodDecl>();
    jj_consume_token(CLASS);
    t = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXTENDS:
      jj_consume_token(EXTENDS);
      t1 = jj_consume_token(ID);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(OPENBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOL:
      case INT:
      case ARRAYOF:
      case ID:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_4;
      }
      fd = nt_FieldDecl();
                                                                      fl.add(fd);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
      md = nt_MethodDecl();
                       ml.add(md);
    }
    jj_consume_token(CLOSEBRACE);
    {if (true) return t1==null ? new ClassDeclSimple(t.image, fl, ml) :
      new ClassDeclExtends(t.image, t1.image, fl, ml);}
    throw new Error("Missing return statement in function");
  }

  final public MethodDecl nt_MethodDecl() throws ParseException {
  MethodDecl m;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROC:
      m = nt_ProcDecl();
      break;
    case FUN:
      m = nt_FunDecl();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return m;}
    throw new Error("Missing return statement in function");
  }

  final public FunDecl nt_FunDecl() throws ParseException {
  Token tok;
  Type t;
  Exp e;
  List<Formal> fl;
  List<Stm> sl = new ArrayList<Stm>();
  Stm st;
    jj_consume_token(FUN);
    t = nt_Type();
    tok = jj_consume_token(ID);
    jj_consume_token(OPENPAREN);
    fl = nt_FormalList();
    jj_consume_token(CLOSEPAREN);
    jj_consume_token(OPENBRACE);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOL:
      case TRUE:
      case FALSE:
      case SELF:
      case INT:
      case ARRAYOF:
      case IF:
      case WHILE:
      case OUTPUT:
      case NEW:
      case ISNULL:
      case OPENBRACE:
      case OPENPAREN:
      case NOT:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      st = nt_Statement();
                      sl.add(st);
    }
    jj_consume_token(RETURN);
    e = nt_Exp();
    jj_consume_token(ENDST);
    jj_consume_token(CLOSEBRACE);
    {if (true) return new FunDecl(t, tok.image, fl, sl, e);}
    throw new Error("Missing return statement in function");
  }

  final public ProcDecl nt_ProcDecl() throws ParseException {
  Token tok;
  List<Formal> fl;
  List<Stm> sl = new ArrayList<Stm>();
  Stm st;
    jj_consume_token(PROC);
    tok = jj_consume_token(ID);
    jj_consume_token(OPENPAREN);
    fl = nt_FormalList();
    jj_consume_token(CLOSEPAREN);
    jj_consume_token(OPENBRACE);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOL:
      case TRUE:
      case FALSE:
      case SELF:
      case INT:
      case ARRAYOF:
      case IF:
      case WHILE:
      case OUTPUT:
      case NEW:
      case ISNULL:
      case OPENBRACE:
      case OPENPAREN:
      case NOT:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_7;
      }
      st = nt_Statement();
                      sl.add(st);
    }
    jj_consume_token(CLOSEBRACE);
    {if (true) return new ProcDecl(tok.image, fl, sl);}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_PrimaryExp() throws ParseException {
  List<Exp> el;
  Exp e;
  Type t;
  Token tok;
  Var v;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      tok = jj_consume_token(INTEGER_LITERAL);
                          {if (true) return new ExpInteger(Integer.parseInt(tok.image));}
      break;
    case TRUE:
      jj_consume_token(TRUE);
           {if (true) return new ExpTrue();}
      break;
    case FALSE:
      jj_consume_token(FALSE);
            {if (true) return new ExpFalse();}
      break;
    case ID:
      v = nt_Var();
               {if (true) return new ExpVar(v);}
      break;
    case SELF:
      jj_consume_token(SELF);
           {if (true) return new ExpSelf();}
      break;
    default:
      jj_la1[11] = jj_gen;
      if (jj_2_1(2)) {
        jj_consume_token(NEW);
        jj_consume_token(ARRAYOF);
        jj_consume_token(OPENPAREN);
        t = nt_Type();
        jj_consume_token(CLOSEPAREN);
        jj_consume_token(OPENSBR);
        e = nt_Exp();
        jj_consume_token(CLOSESBR);
    {if (true) return new ExpNewArray(t, e);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NEW:
          jj_consume_token(NEW);
          jj_consume_token(OBJECT);
          tok = jj_consume_token(ID);
          jj_consume_token(OPENPAREN);
          el = nt_ExpList();
          jj_consume_token(CLOSEPAREN);
    {if (true) return new ExpNewObject(tok.image, el);}
          break;
        case NOT:
          jj_consume_token(NOT);
          e = nt_PrimaryExp();
                            {if (true) return new ExpNot(e);}
          break;
        case ISNULL:
          jj_consume_token(ISNULL);
          e = nt_PrimaryExp();
                               {if (true) return new ExpIsnull(e);}
          break;
        case OPENPAREN:
          jj_consume_token(OPENPAREN);
          e = nt_Exp();
          jj_consume_token(CLOSEPAREN);
                                        {if (true) return e;}
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public List<Formal> nt_FormalList() throws ParseException {
  Token tok;
  Type t;
  Formal fr;
  List<Formal> fl = new ArrayList<Formal>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOL:
    case INT:
    case ARRAYOF:
    case ID:
      t = nt_Type();
      tok = jj_consume_token(ID);
                          fl.add(new Formal(t, tok.image));
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_8;
        }
        fr = nt_FormalRest();
                          fl.add(fr);
      }
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    {if (true) return fl;}
    throw new Error("Missing return statement in function");
  }

  final public Formal nt_FormalRest() throws ParseException {
  Token tok;
  Type t;
    jj_consume_token(COMMA);
    t = nt_Type();
    tok = jj_consume_token(ID);
                                 {if (true) return new Formal(t, tok.image);}
    throw new Error("Missing return statement in function");
  }

  final public Stm nt_Statement() throws ParseException {
  StmBlock block, block1;
  Type t;
  Token tok;
  Var v;
  Exp e, e1, e2;
  List<Exp> el;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPENBRACE:
      block = nt_Block();
                     {if (true) return block;}
      break;
    default:
      jj_la1[16] = jj_gen;
      if (jj_2_2(2)) {
        //type and var could both start with ID
          t = nt_Type();
        tok = jj_consume_token(ID);
        jj_consume_token(ENDST);
                                 {if (true) return new StmVarDecl(t, tok.image);}
      } else if (jj_2_3(2)) {
        //primaryexp could start with ID, but won't have an EQUALS after
          v = nt_Var();
        jj_consume_token(EQUALS);
        e = nt_Exp();
        jj_consume_token(ENDST);
                                           {if (true) return new StmAssign(v, e);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case TRUE:
        case FALSE:
        case SELF:
        case NEW:
        case ISNULL:
        case OPENPAREN:
        case NOT:
        case INTEGER_LITERAL:
        case ID:
          e = nt_PrimaryExp();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPENSBR:
            jj_consume_token(OPENSBR);
            e1 = nt_Exp();
            jj_consume_token(CLOSESBR);
            jj_consume_token(EQUALS);
            e2 = nt_Exp();
            jj_consume_token(ENDST);
    {if (true) return new StmArrayAssign(e, e1, e2);}
            break;
          case DOT:
            jj_consume_token(DOT);
            tok = jj_consume_token(ID);
            jj_consume_token(OPENPAREN);
            el = nt_ExpList();
            jj_consume_token(CLOSEPAREN);
            jj_consume_token(ENDST);
    {if (true) return new StmCall(e, tok.image, el);}
            break;
          default:
            jj_la1[15] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        case IF:
          jj_consume_token(IF);
          jj_consume_token(OPENPAREN);
          e = nt_Exp();
          jj_consume_token(CLOSEPAREN);
          jj_consume_token(THEN);
          block = nt_Block();
          jj_consume_token(ELSE);
          block1 = nt_Block();
    {if (true) return new StmIf(e, block, block1);}
          break;
        case WHILE:
          jj_consume_token(WHILE);
          jj_consume_token(OPENPAREN);
          e = nt_Exp();
          jj_consume_token(CLOSEPAREN);
          jj_consume_token(DO);
          block = nt_Block();
    {if (true) return new StmWhile(e, block);}
          break;
        case OUTPUT:
          jj_consume_token(OUTPUT);
          e = nt_Exp();
          jj_consume_token(ENDST);
                                {if (true) return new StmOutput(e);}
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public StmBlock nt_Block() throws ParseException {
  Stm stm;
  List<Stm> block = new ArrayList<Stm>();
    jj_consume_token(OPENBRACE);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOL:
      case TRUE:
      case FALSE:
      case SELF:
      case INT:
      case ARRAYOF:
      case IF:
      case WHILE:
      case OUTPUT:
      case NEW:
      case ISNULL:
      case OPENBRACE:
      case OPENPAREN:
      case NOT:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_9;
      }
      stm = nt_Statement();
                                   block.add(stm);
    }
    jj_consume_token(CLOSEBRACE);
    {if (true) return new StmBlock(block);}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_Exp() throws ParseException {
  Token tok;
  boolean pe = true;
  Exp pexp1, pexp2;
  Op op;
  List<Exp> el;
    pexp1 = nt_PrimaryExp();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
    case OPENSBR:
    case OP:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
        tok = jj_consume_token(OP);
    switch(tok.image) {
      case "and"        : op=Op.AND; break;
      case "div"        : op=Op.DIV; break;
      case "<"          : op=Op.LESSTHAN; break;
      case "=="         : op=Op.EQUALS; break;
      case "+"          : op=Op.PLUS; break;
      case "-"          : op=Op.MINUS; break;
      case "*"          : op=Op.TIMES; break;
      default           : op=null;
    }
        pexp2 = nt_PrimaryExp();
    {if (true) return new ExpOp(pexp1, op, pexp2);}
        break;
      case OPENSBR:
        jj_consume_token(OPENSBR);
        pexp2 = nt_Exp();
        jj_consume_token(CLOSESBR);
      {if (true) return new ExpArrayLookup(pexp1, pexp2);}
        break;
      case DOT:
        jj_consume_token(DOT);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LENGTH:
          jj_consume_token(LENGTH);
                        {if (true) return new ExpArrayLength(pexp1);}
          break;
        case ID:
          tok = jj_consume_token(ID);
          jj_consume_token(OPENPAREN);
          el = nt_ExpList();
          jj_consume_token(CLOSEPAREN);
        {if (true) return new ExpCall(pexp1, tok.image, el);}
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
       {if (true) return pexp1;}
    throw new Error("Missing return statement in function");
  }

  final public Type nt_Type() throws ParseException {
  Type t;
  Token tok;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAYOF:
      jj_consume_token(ARRAYOF);
      jj_consume_token(OPENPAREN);
      t = nt_Type();
      jj_consume_token(CLOSEPAREN);
                                                   {if (true) return new TypeArray(t);}
      break;
    case BOOL:
      jj_consume_token(BOOL);
           {if (true) return new TypeBoolean();}
      break;
    case INT:
      jj_consume_token(INT);
          {if (true) return new TypeInt();}
      break;
    case ID:
      tok = jj_consume_token(ID);
             {if (true) return new TypeClassType(tok.image);}
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public FieldDecl nt_FieldDecl() throws ParseException {
  Type t;
  Token tok;
    t = nt_Type();
    tok = jj_consume_token(ID);
    jj_consume_token(ENDST);
                                 {if (true) return new FieldDecl(t, tok.image);}
    throw new Error("Missing return statement in function");
  }

  final public Var nt_Var() throws ParseException {
  Token t;
    t = jj_consume_token(ID);
           {if (true) return new Var(t.image);}
    throw new Error("Missing return statement in function");
  }

  final public List<Exp> nt_ExpList() throws ParseException {
  Exp e;
  List<Exp> el = new ArrayList<Exp>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case SELF:
    case NEW:
    case ISNULL:
    case OPENPAREN:
    case NOT:
    case INTEGER_LITERAL:
    case ID:
      e = nt_Exp();
                el.add(e);
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_10;
        }
        e = nt_ExpRest();
                                               el.add(e);
      }
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    {if (true) return el;}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_ExpRest() throws ParseException {
  Exp e;
    jj_consume_token(COMMA);
    e = nt_Exp();
                       {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public void eof() throws ParseException {
    jj_consume_token(0);
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(BOOL)) return true;
    return false;
  }

  private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) {
    jj_scanpos = xsp;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(ARRAYOF)) return true;
    if (jj_scan_token(OPENPAREN)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(ARRAYOF)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(EQUALS)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MooplParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[25];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffff00,0xffffff00,0xffffff00,0x100,0x400,0x800,0x62000,0x300,0x300,0x154fe000,0x154fe000,0x1c000,0x14000000,0x40000000,0x62000,0x20000000,0x0,0x1549c000,0x154fe000,0x2000000,0x20000000,0x20000000,0x62000,0x40000000,0x1401c000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x7ff,0x1ff,0x7ff,0x0,0x0,0x0,0x400,0x0,0x0,0x694,0x694,0x600,0x90,0x0,0x400,0x1,0x4,0x690,0x694,0x400,0x101,0x101,0x400,0x0,0x690,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[3];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MooplParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MooplParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MooplParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MooplParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MooplParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MooplParser(MooplParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MooplParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[43];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 25; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 43; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
