/* Generated By:JavaCC: Do not edit this line. MooplParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MooplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROC = 8;
  /** RegularExpression Id. */
  int FUN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int SELF = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int ARRAYOF = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int OUTPUT = 24;
  /** RegularExpression Id. */
  int LENGTH = 25;
  /** RegularExpression Id. */
  int NEW = 26;
  /** RegularExpression Id. */
  int OBJECT = 27;
  /** RegularExpression Id. */
  int ISNULL = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int EQUALS = 31;
  /** RegularExpression Id. */
  int OPENSBR = 32;
  /** RegularExpression Id. */
  int CLOSESBR = 33;
  /** RegularExpression Id. */
  int OPENBRACE = 34;
  /** RegularExpression Id. */
  int CLOSEBRACE = 35;
  /** RegularExpression Id. */
  int OPENPAREN = 36;
  /** RegularExpression Id. */
  int CLOSEPAREN = 37;
  /** RegularExpression Id. */
  int ENDSTAT = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int OP = 40;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 41;
  /** RegularExpression Id. */
  int ID = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"proc\"",
    "\"fun\"",
    "\"class\"",
    "\"extends\"",
    "\"return\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"self\"",
    "\"int\"",
    "\"arrayof\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"output\"",
    "\"length\"",
    "\"new\"",
    "\"object\"",
    "\"isnull\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"!\"",
    "<OP>",
    "<INTEGER_LITERAL>",
    "<ID>",
  };

}
